### ISSUE TITLE
Consultar la temperatura

### ISSUE THREAD

**Issue by gianfranco-s** [yamil-90/weather-app-react-native#13]
Cuando se seleccione una ciudad del listado, se deberá consultar un servicio de Clima (OpenWeatherMap, por ejemplo) para obtener la temperatura de esa ciudad.
Deberás realizar una petición web a través de la API del servicio, trabajar con la respuesta del servicio del clima para obtener la temperatura de la ciudad y mostrarla en la pantalla.

**Comment by gianfranco-s** [comment]
@yamil-90 said
aca es donde podriamos mejorar la app con un listado que muestre las ciudades con temperaturas y manejar las alertas

**Comment by yamil-90** [comment]
ya resuelto en otros issues
