### ISSUE TITLE
Base de datos

### ISSUE THREAD

**Issue by gianfranco-s** [yamil-90/weather-app-react-native#6]
Es necesario que los datos se conserven a lo largo del ciclo de vida de la aplicación.
Esto significa que cuando se reinicie la app se deberá conservar el listado de ciudades que previamente se había guardado.

**Comment by gianfranco-s** [comment]
@yamil-90 said
viendo sqlite creo que es la mejor opcion para la app ya que asi zafamos de hacer el login y todo lo demas y solo guardamos el listado de ciudades y preferencias en el celu y no dependemos de una base de datos externa

**Comment by yamil-90** [comment]
terminada y solucionados los bugs cuando se iniciaba la app por primera vez
