### ISSUE TITLE
Animación de inicio

### ISSUE THREAD

**Issue by gianfranco-s** [yamil-90/weather-app-react-native#8]

**Comment by gianfranco-s** [comment]
@yamil-90 said
idea: varias nubes moviendose de derecha a izquierda a diferentes velocidades y luego una nube mas grande para y las oculta para que luego quede el logo en el medio

**Comment by gianfranco-s** [comment]
@yamil-90 said
esta hecha pero creo que necesita mejores colores, mejor logo y quiza una animacion mejor de las nubes moviendose.

**Comment by yamil-90** [comment]
good enough
