### ISSUE TITLE
Agregar ciudades al listado de "Mis ciudades"

### ISSUE THREAD

**Issue by gianfranco-s** [yamil-90/weather-app-react-native#9]
- [x] Crear formulario para agregar ciudades
- [x] Programar la validación de datos
- [x] Conectar a la base de datos
- [x] Agregar la función de agregar ciudades a la base de datos
- [ ] El input de ciudades debe ser un buscador con autocompletar
- [x] Después de elegir la ciudad, debe aparecer un mapa con la ciudad elegida
- [ ] Opcional: elegir ciudad a partir de un mapa

**Comment by gianfranco-s** [comment]
@yamil-90 said
por ahora funciona pero hay que buscar la forma de agregar solo ciudades validas porque puedo agregar una ciudad con un typo y me da error en screen "mis ciudades"

**Comment by yamil-90** [comment]
cerrado con las features actuales
